<?php

// Interaktiver Leser fuer die REST-API der Smartbox/IQ-Box.
// Leere Eingabe zeigt alle Werte, "raw" schreibt die komplette JSON-Antwort als Datei, "q" beendet.
// Eingaben mit % funktionieren wie SQL LIKE, z.B. "%battery%power%".

$baseUrl = 'http://192.168.178.26';
$username = 'installer';
$password = 'sfjimorx';
$cookieFile = __DIR__ . '/ampere_cookie.txt';
$baseUrlExplicit = isset($argv[1]) && trim($argv[1]) !== '';
$showLoginResult = true;

date_default_timezone_set('Europe/Berlin');

if ($baseUrlExplicit) {
    $baseUrl = normalizeBaseUrl($argv[1]);
} else {
    $baseUrl = normalizeBaseUrl($baseUrl);
}

function normalizeBaseUrl(string $value): string
{
    $value = trim($value);
    if ($value === '') {
        return '';
    }

    if (!preg_match('~^https?://~i', $value)) {
        $value = 'http://' . $value;
    }

    return rtrim($value, '/');
}

function ampereLogin(string $baseUrl, string $username, string $password, string $cookieFile): void
{
    global $showLoginResult;

    $dir = dirname($cookieFile);
    if (!is_dir($dir)) {
        @mkdir($dir, 0770, true);
    }

    $ch = curl_init($baseUrl . '/auth/login');
    curl_setopt_array($ch, [
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => http_build_query([
            'username' => $username,
            'password' => $password,
        ]),
        CURLOPT_COOKIEJAR => $cookieFile,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HEADER => true,
        CURLOPT_TIMEOUT => 10,
        CURLOPT_FOLLOWLOCATION => false,
    ]);

    $response = curl_exec($ch);
    if ($response === false) {
        $error = curl_error($ch);
        curl_close($ch);
        throw new RuntimeException('Login failed: ' . $error);
    }

    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $headerSize = (int)curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    curl_close($ch);
    $headers = substr((string)$response, 0, $headerSize);
    $body = substr((string)$response, $headerSize);

    if (!is_file($cookieFile) || filesize($cookieFile) === 0) {
        writeCookieJarFromHeaders($baseUrl, $headers, $cookieFile);
    }

    if ($showLoginResult) {
        printLoginResult($baseUrl, $code, $headers, $body, $cookieFile);
    }

    if (!in_array($code, [200, 302, 303], true)) {
        throw new RuntimeException("Login HTTP error $code");
    }
}

function printLoginResult(string $baseUrl, int $code, string $headers, string $response, string $cookieFile): void
{
    $cookieInfo = 'keine Cookie-Datei';
    if (is_file($cookieFile)) {
        $cookieInfo = filesize($cookieFile) . ' Bytes';
        $cookieText = (string)file_get_contents($cookieFile);
        if (preg_match('/\s(kiwisessionid)\s+([^\s]+)/', $cookieText, $matches)) {
            $cookieInfo .= ', ' . $matches[1] . '=' . maskValue($matches[2]);
        }
    }

    $setCookie = '<kein Set-Cookie>';
    if (preg_match('/^set-cookie:\s*(.+)$/mi', $headers, $matches)) {
        $setCookie = maskCookieHeader(trim($matches[1]));
    }

    $body = trim($response);
    if ($body === '') {
        $body = '<leer>';
    } elseif (strlen($body) > 160) {
        $body = substr($body, 0, 160) . '...';
    }

    echo "Login POST $baseUrl/auth/login -> HTTP $code, Set-Cookie: $setCookie, Cookie-Datei: $cookieInfo, Antwort: $body" . PHP_EOL;
}

function maskValue(string $value): string
{
    if (strlen($value) <= 8) {
        return '***';
    }

    return substr($value, 0, 4) . '...' . substr($value, -4);
}

function maskCookieHeader(string $header): string
{
    return preg_replace_callback('/(kiwisessionid=)([^;]+)/', function (array $matches): string {
        return $matches[1] . maskValue($matches[2]);
    }, $header) ?? $header;
}

function writeCookieJarFromHeaders(string $baseUrl, string $headers, string $cookieFile): void
{
    if (!preg_match('/^set-cookie:\s*kiwisessionid=([^;]+)/mi', $headers, $matches)) {
        return;
    }

    $host = parse_url($baseUrl, PHP_URL_HOST) ?: '192.168.178.26';
    $value = trim($matches[1]);
    $expires = time() + 3600;
    if (preg_match('/Max-Age=(\d+)/i', $headers, $maxAge)) {
        $expires = time() + (int)$maxAge[1];
    }

    $dir = dirname($cookieFile);
    if (!is_dir($dir)) {
        @mkdir($dir, 0770, true);
    }

    $content = "# Netscape HTTP Cookie File\n";
    $content .= "# generated by json-solar-rest-loop.php fallback\n\n";
    $content .= "#HttpOnly_$host\tFALSE\t/\tFALSE\t$expires\tkiwisessionid\t$value\n";
    @file_put_contents($cookieFile, $content);
}

function ampereRequest(string $baseUrl, string $path, string $username, string $password, string $cookieFile, bool $retry = false): array
{
    if (!file_exists($cookieFile)) {
        ampereLogin($baseUrl, $username, $password, $cookieFile);
    }

    $ch = curl_init($baseUrl . $path);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_TIMEOUT => 15,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_HTTPHEADER => ['Accept: application/json', 'Connection: close'],
    ]);

    $response = curl_exec($ch);
    if ($response === false) {
        $error = curl_error($ch);
        curl_close($ch);
        throw new RuntimeException('cURL error: ' . $error);
    }

    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if (in_array($code, [301, 302, 303, 401, 403], true)) {
        if ($retry) {
            throw new RuntimeException("Auth failed after retry HTTP $code");
        }

        @unlink($cookieFile);
        ampereLogin($baseUrl, $username, $password, $cookieFile);
        return ampereRequest($baseUrl, $path, $username, $password, $cookieFile, true);
    }

    if ($code === 404) {
        if ($retry) {
            throw new RuntimeException("HTTP 404 after login");
        }

        @unlink($cookieFile);
        ampereLogin($baseUrl, $username, $password, $cookieFile);
        return ampereRequest($baseUrl, $path, $username, $password, $cookieFile, true);
    }

    if ($code !== 200) {
        throw new RuntimeException("HTTP error $code");
    }

    return [
        'ok' => true,
        'http_code' => 200,
        'data' => (string)$response,
    ];
}

function loadItemsRaw(string $baseUrl, string $username, string $password, string $cookieFile): array
{
    try {
        $result = ampereRequest($baseUrl, '/rest/items', $username, $password, $cookieFile);
    } catch (Throwable $e) {
        if (!str_contains($e->getMessage(), '404')) {
            throw $e;
        }

        $result = ampereRequest($baseUrl, '/rest/items/', $username, $password, $cookieFile);
    }
    $data = json_decode($result['data'], true);

    if (json_last_error() !== JSON_ERROR_NONE || !is_array($data)) {
        throw new RuntimeException('Invalid JSON response: ' . json_last_error_msg());
    }

    return $data;
}

function loadItemsRawWithFallbacks(string &$baseUrl, bool $baseUrlExplicit, string $username, string $password, string $cookieFile): array
{
    $candidates = [$baseUrl];

    $candidates = array_values(array_unique(array_map('normalizeBaseUrl', $candidates)));
    $lastError = null;
    $firstError = null;

    foreach ($candidates as $candidate) {
        echo "Versuche REST: $candidate/rest/items" . PHP_EOL;
        try {
            $data = loadItemsRaw($candidate, $username, $password, $cookieFile);
            $baseUrl = $candidate;
            return $data;
        } catch (Throwable $e) {
            $lastError = $e;
            if ($firstError === null) {
                $firstError = $e;
            }
            echo "  nicht ok: " . $e->getMessage() . PHP_EOL;
        }
    }

    throw new RuntimeException($firstError ? $firstError->getMessage() : ($lastError ? $lastError->getMessage() : 'kein REST-Endpunkt erreichbar'));
}

function safeLoadItemsRaw(string &$baseUrl, bool $baseUrlExplicit, string $username, string $password, string $cookieFile, array &$rawData): array
{
    try {
        $rawData = loadItemsRawWithFallbacks($baseUrl, $baseUrlExplicit, $username, $password, $cookieFile);
        $items = normalizeItems($rawData);
        echo "Aktive REST-URL: $baseUrl" . PHP_EOL;
        echo 'Items geladen: ' . count($items) . PHP_EOL;
        return $items;
    } catch (Throwable $e) {
        $rawData = [];
        echo 'WARNUNG: REST-Daten konnten nicht geladen werden: ' . $e->getMessage() . PHP_EOL;
        echo 'Hinweis: Die Schleife bleibt offen. Du kannst direkte Pfade eingeben, z.B. /rest, /rest/items oder /em-setup/.' . PHP_EOL;
        return [];
    }
}

function executePathCommand(string $baseUrl, string $path, string $username, string $password, string $cookieFile): void
{
    try {
        if (!is_file($cookieFile) || filesize($cookieFile) === 0) {
            ampereLogin($baseUrl, $username, $password, $cookieFile);
        }

        $result = requestPathRaw($baseUrl, $path, $cookieFile);
        if (in_array($result['code'], [301, 302, 303, 401, 403], true)) {
            @unlink($cookieFile);
            ampereLogin($baseUrl, $username, $password, $cookieFile);
            $result = requestPathRaw($baseUrl, $path, $cookieFile);
        }

        printPathResult($path, $result);
    } catch (Throwable $e) {
        echo 'WARNUNG: ' . $e->getMessage() . PHP_EOL;
    }
}

function requestPathRaw(string $baseUrl, string $path, string $cookieFile): array
{
    $url = $baseUrl . $path;
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_COOKIEJAR => $cookieFile,
        CURLOPT_TIMEOUT => 15,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_HEADER => true,
        CURLOPT_HTTPHEADER => ['Accept: application/json,text/plain,text/html,*/*', 'Connection: close'],
    ]);

    $response = curl_exec($ch);
    if ($response === false) {
        $error = curl_error($ch);
        curl_close($ch);
        throw new RuntimeException('cURL error: ' . $error);
    }

    $code = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $type = (string)curl_getinfo($ch, CURLINFO_CONTENT_TYPE);
    $headerSize = (int)curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    curl_close($ch);

    $headers = substr((string)$response, 0, $headerSize);
    $body = substr((string)$response, $headerSize);

    return [
        'url' => $url,
        'code' => $code,
        'type' => $type,
        'headers' => $headers,
        'body' => $body,
    ];
}

function printPathResult(string $path, array $result): void
{
    echo $path . ' -> HTTP ' . $result['code'];
    if ($result['type'] !== '') {
        echo ' ' . $result['type'];
    }
    if (preg_match('/^location:\s*(.+)$/mi', (string)$result['headers'], $matches)) {
        echo ' Location: ' . trim($matches[1]);
    }
    echo PHP_EOL;

    $body = trim((string)$result['body']);
    if ($body === '') {
        echo '<leer>' . PHP_EOL;
        return;
    }

    if (str_contains(strtolower((string)$result['type']), 'javascript') || preg_match('/\.m?js(?:\?|$)/i', $path)) {
        printScriptHints($body);
        return;
    }

    $decoded = json_decode($body, true);
    if (json_last_error() === JSON_ERROR_NONE) {
        echo json_encode($decoded, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . PHP_EOL;
        return;
    }

    if (strlen($body) > 4000) {
        $body = substr($body, 0, 4000) . PHP_EOL . '... gekuerzt ...';
    }
    echo $body . PHP_EOL;
}

function printScriptHints(string $body): void
{
    $hints = collectApiLikeStrings($body);
    $methodHints = collectHttpMethodHints($body);

    if (!$hints && !$methodHints) {
        echo 'Keine API-Hinweise in dieser JavaScript-Datei gefunden.' . PHP_EOL;
        return;
    }

    if ($methodHints) {
        echo 'HTTP-Aufrufe/Pfade:' . PHP_EOL;
        foreach (array_slice($methodHints, 0, 120) as $hint) {
            echo '  ' . $hint . PHP_EOL;
        }
    }

    if ($hints) {
        echo 'Weitere Pfad-Hinweise:' . PHP_EOL;
        foreach (array_slice($hints, 0, 160) as $hint) {
            echo '  ' . $hint . PHP_EOL;
        }
    }
}

function collectHttpMethodHints(string $text): array
{
    $values = [];

    preg_match_all('/httpClient\.request\("([^"]+)",`\$\{this\.configuration\.basePath\}([^`]+)`/i', $text, $matches, PREG_SET_ORDER);
    foreach ($matches as $match) {
        $values[strtoupper($match[1]) . ' ' . $match[2]] = true;
    }

    preg_match_all('/httpClient\.request\("([^"]+)","([^"]+)"/i', $text, $matches, PREG_SET_ORDER);
    foreach ($matches as $match) {
        $values[strtoupper($match[1]) . ' ' . $match[2]] = true;
    }

    preg_match_all('/\.(get|post|put|delete|patch)\(`\$\{this\.configuration\.basePath\}([^`]+)`/i', $text, $matches, PREG_SET_ORDER);
    foreach ($matches as $match) {
        $values[strtoupper($match[1]) . ' ' . $match[2]] = true;
    }

    return array_keys($values);
}

function executeJsFind(string $baseUrl, string $needle, string $cookieFile): void
{
    $needle = trim($needle);
    if ($needle === '') {
        echo 'WARNUNG: Suchtext fehlt, Beispiel: jsfind soc' . PHP_EOL;
        return;
    }

    echo "Suche in EM.setup JavaScript nach: $needle" . PHP_EOL;
    $assets = collectEmSetupAssets($baseUrl, $cookieFile);
    if (!$assets) {
        echo 'WARNUNG: Keine JavaScript-Dateien gefunden.' . PHP_EOL;
        return;
    }

    $totalHits = 0;
    foreach ($assets as $asset) {
        if (!preg_match('/\.m?js(?:\?|$)/i', $asset)) {
            continue;
        }

        $assetUrl = str_starts_with($asset, 'http') ? $asset : $baseUrl . '/' . ltrim($asset, '/');
        $res = curlRaw($assetUrl, $cookieFile);
        if (!$res['ok']) {
            continue;
        }

        $hits = findTextContexts($res['body'], $needle, 180, 8);
        if (!$hits) {
            continue;
        }

        echo PHP_EOL . "Asset $asset" . PHP_EOL;
        foreach ($hits as $hit) {
            echo '  ...' . $hit . '...' . PHP_EOL;
        }
        $totalHits += count($hits);
    }

    if ($totalHits === 0) {
        echo 'Keine Treffer gefunden.' . PHP_EOL;
    } else {
        echo PHP_EOL . "Treffer gesamt: $totalHits" . PHP_EOL;
    }
}

function collectEmSetupAssets(string $baseUrl, string $cookieFile): array
{
    $startPaths = [
        '/em-setup/',
        '/em-setup/dashboard',
        '/em-setup/hems-configurator/devices',
    ];
    $assets = [
        '/kiwios-components/app-frame.js' => true,
    ];

    foreach ($startPaths as $path) {
        $res = curlRaw($baseUrl . $path, $cookieFile);
        if (!$res['ok']) {
            continue;
        }
        foreach (extractAssetPaths($res['body']) as $asset) {
            $assets[resolveAssetPath($path, $asset)] = true;
        }
    }

    $seen = [];
    $queue = array_keys($assets);
    while ($queue && count($seen) < 80) {
        $asset = array_shift($queue);
        if (isset($seen[$asset])) {
            continue;
        }
        $seen[$asset] = true;

        if (!preg_match('/\.m?js(?:\?|$)/i', $asset)) {
            continue;
        }

        $assetUrl = str_starts_with($asset, 'http') ? $asset : $baseUrl . '/' . ltrim($asset, '/');
        $res = curlRaw($assetUrl, $cookieFile);
        if (!$res['ok']) {
            continue;
        }

        foreach (extractAssetPaths($res['body']) as $nextAsset) {
            $resolved = resolveAssetPath($asset, $nextAsset);
            if (!isset($seen[$resolved])) {
                $queue[] = $resolved;
            }
        }
    }

    return array_keys($seen);
}

function findTextContexts(string $text, string $needle, int $contextLength, int $limit): array
{
    $hits = [];
    $needleLength = strlen($needle);

    if ($needleLength <= 3) {
        $pattern = '/(?<![A-Za-z0-9_])' . preg_quote($needle, '/') . '(?![A-Za-z0-9_])/i';
        preg_match_all($pattern, $text, $matches, PREG_OFFSET_CAPTURE);
        $positions = array_map(static fn(array $match): int => $match[1], $matches[0] ?? []);
    } else {
        $positions = [];
        $offset = 0;
        while (($pos = stripos($text, $needle, $offset)) !== false) {
            $positions[] = $pos;
            $offset = $pos + max(1, $needleLength);
            if (count($positions) >= $limit) {
                break;
            }
        }
    }

    foreach ($positions as $pos) {
        $start = max(0, $pos - $contextLength);
        $length = $needleLength + ($contextLength * 2);
        $snippet = substr($text, $start, $length);
        $snippet = preg_replace('/\s+/', ' ', $snippet) ?? $snippet;
        if (strlen($snippet) > 420) {
            $snippet = substr($snippet, 0, 420);
        }
        $hits[] = $snippet;
        if (count($hits) >= $limit) {
            break;
        }
    }

    return $hits;
}

function probeEndpoint(string $baseUrl, string $path, string $username, string $password, string $cookieFile): array
{
    @unlink($cookieFile);
    try {
        ampereLogin($baseUrl, $username, $password, $cookieFile);
    } catch (Throwable $e) {
        return [
            'path' => $path,
            'code' => 'login: ' . $e->getMessage(),
            'type' => '',
            'body' => '',
        ];
    }

    $url = $baseUrl . $path;
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_TIMEOUT => 8,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_HEADER => true,
        CURLOPT_HTTPHEADER => ['Accept: application/json,text/plain,*/*', 'Connection: close'],
    ]);

    $response = curl_exec($ch);
    if ($response === false) {
        $error = curl_error($ch);
        curl_close($ch);
        return [
            'path' => $path,
            'code' => 'curl: ' . $error,
            'type' => '',
            'body' => '',
        ];
    }

    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $headerSize = (int)curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $type = (string)curl_getinfo($ch, CURLINFO_CONTENT_TYPE);
    curl_close($ch);
    $headers = substr((string)$response, 0, $headerSize);
    $response = substr((string)$response, $headerSize);

    $body = preg_replace('/\s+/', ' ', trim((string)$response)) ?? '';
    if (strlen($body) > 120) {
        $body = substr($body, 0, 120) . '...';
    }
    if (preg_match('/^location:\s*(.+)$/mi', $headers, $matches)) {
        $body = 'Location: ' . trim($matches[1]) . ($body !== '' ? ' | ' . $body : '');
    }

    return [
        'path' => $path,
        'code' => (string)$code,
        'type' => $type,
        'body' => $body,
    ];
}

function printEndpointProbe(string $baseUrl, string $username, string $password, string $cookieFile): void
{
    echo PHP_EOL . "Diagnose fuer $baseUrl" . PHP_EOL;
    foreach ([
        '/',
        '/auth/login',
        '/rest',
        '/rest/',
        '/rest/tenant-service',
        '/rest/tenant-service/',
        '/rest/tenant-service/tenants',
        '/rest/tenant-service/current-tenant',
        '/tenant-service',
        '/tenant-service/',
        '/tenant-service/tenants',
        '/tenant-service/current-tenant',
        '/tenant-service/api/tenants',
        '/rest/items',
        '/rest/items/',
        '/rest/items?recursive=false',
        '/openhab/rest/items',
        '/api/rest/items',
        '/api/items',
        '/em-setup',
        '/em-setup/',
        '/em-setup/api',
        '/em-setup/rest',
        '/em-setup/backend',
        '/em-setup/hems-configurator/devices',
        '/em-setup/hems-configurator/api/devices',
        '/em-setup/hems-configurator/rest/devices',
        '/kiwios-components/app-frame.js',
    ] as $path) {
        $probe = probeEndpoint($baseUrl, $path, $username, $password, $cookieFile);
        echo str_pad($probe['path'], 28) . ' HTTP ' . $probe['code'];
        if ($probe['type'] !== '') {
            echo ' ' . $probe['type'];
        }
        if ($probe['body'] !== '') {
            echo ' | ' . $probe['body'];
        }
        echo PHP_EOL;
    }
}

function curlRaw(string $url, string $cookieFile): array
{
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_TIMEOUT => 10,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTPHEADER => ['Accept: text/html,application/javascript,application/json,*/*', 'Connection: close'],
    ]);

    $response = curl_exec($ch);
    if ($response === false) {
        $error = curl_error($ch);
        curl_close($ch);
        return ['ok' => false, 'code' => 0, 'type' => '', 'body' => '', 'error' => $error];
    }

    $code = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $type = (string)curl_getinfo($ch, CURLINFO_CONTENT_TYPE);
    curl_close($ch);

    return ['ok' => $code >= 200 && $code < 400, 'code' => $code, 'type' => $type, 'body' => (string)$response, 'error' => ''];
}

function printEmSetupHints(string $baseUrl, string $cookieFile): void
{
    echo PHP_EOL . "Suche EM.setup API-Hinweise" . PHP_EOL;
    $startPaths = [
        '/em-setup/dashboard',
        '/em-setup/hems-configurator/devices',
    ];

    $assets = [];
    foreach ($startPaths as $path) {
        $url = $baseUrl . $path;
        $res = curlRaw($url, $cookieFile);
        echo "$path HTTP {$res['code']} {$res['type']}" . PHP_EOL;
        if (!$res['ok']) {
            continue;
        }

        foreach (extractAssetPaths($res['body']) as $asset) {
            $assets[resolveAssetPath($path, $asset)] = true;
        }
        printApiLikeStrings($res['body']);
    }

    if ($assets) {
        echo "Assets gefunden:" . PHP_EOL;
        foreach (array_keys($assets) as $asset) {
            echo "  $asset" . PHP_EOL;
        }
    }

    $seenAssets = [];
    $queue = array_keys($assets);
    $count = 0;
    while ($queue) {
        if ($count >= 40) {
            break;
        }
        $asset = array_shift($queue);
        if (isset($seenAssets[$asset])) {
            continue;
        }
        $seenAssets[$asset] = true;
        $assetUrl = str_starts_with($asset, 'http') ? $asset : $baseUrl . '/' . ltrim($asset, '/');
        $res = curlRaw($assetUrl, $cookieFile);
        if (!$res['ok']) {
            continue;
        }

        foreach (extractAssetPaths($res['body']) as $nextAsset) {
            $resolved = resolveAssetPath($asset, $nextAsset);
            if (!isset($seenAssets[$resolved])) {
                $queue[] = $resolved;
            }
        }

        $found = collectApiLikeStrings($res['body']);
        if (!$found) {
            continue;
        }

        echo "Asset $asset" . PHP_EOL;
        foreach (array_slice($found, 0, 25) as $hint) {
            echo "  $hint" . PHP_EOL;
        }
        $count++;
    }
}

function extractAssetPaths(string $html): array
{
    preg_match_all('/(?:src|href)=["\']([^"\']+\.(?:js|mjs|css)(?:\?[^"\']*)?)["\']/i', $html, $matches);
    $assets = $matches[1] ?? [];
    preg_match_all('/["\']([^"\']+\.(?:js|mjs|css)(?:\?[^"\']*)?)["\']/i', $html, $stringMatches);
    foreach ($stringMatches[1] ?? [] as $asset) {
        if (str_contains($asset, '://') || str_starts_with($asset, 'data:')) {
            continue;
        }
        $assets[] = $asset;
    }

    return array_values(array_unique($assets));
}

function resolveAssetPath(string $currentPath, string $asset): string
{
    if (str_starts_with($asset, 'http') || str_starts_with($asset, '/')) {
        return $asset;
    }

    $dir = rtrim(dirname('/' . ltrim($currentPath, '/')), '/');
    if ($dir === '') {
        $dir = '/';
    }

    return rtrim($dir, '/') . '/' . ltrim($asset, '/');
}

function collectApiLikeStrings(string $text): array
{
    preg_match_all('~["\']((?:/|https?://)[^"\']*(?:api|rest|devices|saj|battery|inverter|meter|hems|em-setup)[^"\']*)["\']~i', $text, $matches);
    $values = [];
    foreach ($matches[1] ?? [] as $value) {
        $value = stripcslashes($value);
        if (strlen($value) > 180) {
            $value = substr($value, 0, 180) . '...';
        }
        $values[$value] = true;
    }

    preg_match_all('#["\'](/(?:[A-Za-z0-9_.~:@!$&()*+,;=/-]+)(?:\?[A-Za-z0-9_.~:@!$&()*+,;=/%-]+)?)["\']#', $text, $pathMatches);
    foreach ($pathMatches[1] ?? [] as $value) {
        if (str_starts_with($value, '/assets/') || str_starts_with($value, '/static/')) {
            continue;
        }
        if (strlen($value) < 4 || strlen($value) > 180) {
            continue;
        }
        $values[$value] = true;
    }

    return array_keys($values);
}

function printApiLikeStrings(string $text): void
{
    foreach (array_slice(collectApiLikeStrings($text), 0, 25) as $hint) {
        echo "  Hinweis: $hint" . PHP_EOL;
    }
}

function normalizeItems(array $data): array
{
    if (isset($data['items']) && is_array($data['items'])) {
        return $data['items'];
    }

    return $data;
}

function normalizeUnit(string $unit): string
{
    $unit = trim($unit);
    $unit = @iconv('UTF-8', 'UTF-8//IGNORE', $unit);
    $unit = str_replace(["\xEF\xBB\xBF", 'Â'], '', $unit);
    return strtolower(trim($unit));
}

function convertState($state): array
{
    $rawState = $state;
    if ($state === null || $state === 'NULL' || $state === 'UNDEF') {
        return [
            'valid' => false,
            'rawState' => $rawState,
            'timestampMs' => '',
            'timestampUnix' => '',
            'datetime' => '',
            'rawValue' => '',
            'rawUnit' => '',
            'value' => '',
            'unit' => '',
        ];
    }

    $stateText = trim((string)$state);
    $timestampMs = '';
    $timestampUnix = '';
    $datetime = '';
    $valuePart = $stateText;

    if (str_contains($stateText, '|')) {
        [$maybeTimestamp, $rest] = explode('|', $stateText, 2);
        if (ctype_digit($maybeTimestamp)) {
            $timestampMs = $maybeTimestamp;
            $seconds = (int)floor(((int)$timestampMs) / 1000);
            $timestampUnix = (string)$seconds;
            $datetime = date('Y-m-d H:i:s', $seconds);
            $valuePart = trim($rest);
        }
    }

    $rawValue = $valuePart;
    $rawUnit = '';
    $value = $valuePart;
    $unit = '';

    if (preg_match('/^\s*([+-]?[0-9]+(?:[.,][0-9]+)?(?:[eE][+-]?[0-9]+)?)\s*(.*?)\s*$/u', $valuePart, $m)) {
        $rawValue = $m[1];
        $rawUnit = $m[2] ?? '';
        $numeric = (float)str_replace(',', '.', $rawValue);
        $unitNormalized = normalizeUnit($rawUnit);

        switch ($unitNormalized) {
            case 'w':
                $value = round($numeric / 1000, 4);
                $unit = 'kW';
                break;
            case 'kw':
                $value = round($numeric, 4);
                $unit = 'kW';
                break;
            case 'wh':
                $value = round($numeric / 1000, 4);
                $unit = 'kWh';
                break;
            case 'ws':
                $value = round($numeric / 3600000, 4);
                $unit = 'kWh';
                break;
            case 'kwh':
                $value = round($numeric, 4);
                $unit = 'kWh';
                break;
            case '%':
                $value = round($numeric, 4);
                $unit = '%';
                break;
            case 'a':
                $value = round($numeric, 4);
                $unit = 'A';
                break;
            case 'v':
                $value = round($numeric, 4);
                $unit = 'V';
                break;
            case 'c':
            case '°c':
                $value = round($numeric, 4);
                $unit = 'C';
                break;
            default:
                $value = round($numeric, 4);
                $unit = $rawUnit;
                break;
        }
    }

    return [
        'valid' => true,
        'rawState' => $rawState,
        'timestampMs' => $timestampMs,
        'timestampUnix' => $timestampUnix,
        'datetime' => $datetime,
        'rawValue' => $rawValue,
        'rawUnit' => $rawUnit,
        'value' => $value,
        'unit' => $unit,
    ];
}

function nameShort(string $name): string
{
    $name = preg_replace('/^sajhybrid_/', '', $name) ?? $name;
    $name = preg_replace('/HSR[0-9A-Z]+_/', '', $name) ?? $name;
    return $name;
}

function likeToRegex(string $pattern): string
{
    $regex = preg_quote($pattern, '/');
    $regex = str_replace('%', '.*', $regex);
    return '/^' . $regex . '$/i';
}

function itemMatches(array $item, string $filter): bool
{
    $filter = trim($filter);
    if ($filter === '') {
        return true;
    }

    $haystacks = [
        (string)($item['name'] ?? ''),
        (string)($item['label'] ?? ''),
        (string)($item['link'] ?? ''),
        (string)($item['state'] ?? ''),
        (string)($item['type'] ?? ''),
    ];

    if (str_contains($filter, '%')) {
        $regex = likeToRegex($filter);
        foreach ($haystacks as $text) {
            if (preg_match($regex, $text)) {
                return true;
            }
        }
        return false;
    }

    foreach ($haystacks as $text) {
        if (strcasecmp($text, $filter) === 0 || stripos($text, $filter) !== false) {
            return true;
        }
    }

    return false;
}

function formatNullable($value): string
{
    if ($value === null) {
        return 'NULL';
    }

    return (string)$value;
}

function printHelp(): void
{
    echo PHP_EOL;
    echo 'Bedienung:' . PHP_EOL;
    echo '  leer          alle Werte anzeigen' . PHP_EOL;
    echo '  text          Suche nach Text in Name, Label, Link, State oder Typ' . PHP_EOL;
    echo '  %text%        LIKE-Suche mit % als Platzhalter, z.B. %battery%power%' . PHP_EOL;
    echo '  r             REST-Daten neu laden' . PHP_EOL;
    echo '  login         Cookie loeschen und neu einloggen' . PHP_EOL;
    echo '  jsfind text   EM.setup JavaScript nach Text durchsuchen, z.B. jsfind soc' . PHP_EOL;
    echo '  /pfad         direkten GET ausfuehren, z.B. /rest, /rest/items, /em-setup/' . PHP_EOL;
    echo '  raw           komplette JSON-Antwort als Datei speichern' . PHP_EOL;
    echo '  ?             diese Hilfe anzeigen' . PHP_EOL;
    echo '  q             beenden' . PHP_EOL;
}

function writeRawJsonFile(array $rawData): string
{
    $file = __DIR__ . '/json-solar-rest-loop-raw.json';
    $json = json_encode($rawData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    if ($json === false) {
        throw new RuntimeException('Raw JSON konnte nicht codiert werden: ' . json_last_error_msg());
    }

    if (file_put_contents($file, $json . PHP_EOL) === false) {
        throw new RuntimeException("Raw JSON konnte nicht geschrieben werden: $file");
    }

    return $file;
}

function printItems(array $items, string $filter): void
{
    $rows = [];
    foreach ($items as $index => $item) {
        if (!is_array($item) || !itemMatches($item, $filter)) {
            continue;
        }

        $state = $item['state'] ?? null;
        $converted = convertState($state);
        $rows[] = [
            'lfnr' => $index,
            'label' => (string)($item['label'] ?? ''),
            'datetime' => $converted['datetime'],
            'timestampMs' => $converted['timestampMs'],
            'timestampUnix' => $converted['timestampUnix'],
            'rawState' => formatNullable($converted['rawState']),
            'rawValue' => (string)$converted['rawValue'],
            'rawUnit' => (string)$converted['rawUnit'],
            'value' => (string)$converted['value'],
            'unit' => (string)$converted['unit'],
            'readOnly' => isset($item['stateDescription']['readOnly'])
                ? ($item['stateDescription']['readOnly'] ? 'true' : 'false')
                : '',
            'nameShort' => nameShort((string)($item['name'] ?? '')),
            'name' => (string)($item['name'] ?? ''),
            'type' => (string)($item['type'] ?? ''),
            'link' => (string)($item['link'] ?? ''),
        ];
    }

    echo PHP_EOL;
    echo 'Treffer: ' . count($rows) . PHP_EOL;
    echo str_repeat('=', 100) . PHP_EOL;

    foreach ($rows as $row) {
        echo '[' . $row['lfnr'] . '] ' . $row['name'] . PHP_EOL;
        echo '    Label:     ' . $row['label'] . PHP_EOL;
        echo '    Kurzname:  ' . $row['nameShort'] . PHP_EOL;
        echo '    Typ:       ' . $row['type'] . PHP_EOL;
        echo '    Raw:       ' . $row['rawState'] . PHP_EOL;
        echo '    Wert:      ' . $row['value'] . ($row['unit'] !== '' ? ' ' . $row['unit'] : '') . PHP_EOL;

        if ($row['rawValue'] !== '' || $row['rawUnit'] !== '') {
            echo '    Rohwert:   ' . $row['rawValue'] . ($row['rawUnit'] !== '' ? ' ' . $row['rawUnit'] : '') . PHP_EOL;
        }

        if ($row['datetime'] !== '') {
            echo '    Zeit:      ' . $row['datetime'] . PHP_EOL;
            echo '    Unix:      ' . $row['timestampUnix'] . PHP_EOL;
            echo '    Unix ms:   ' . $row['timestampMs'] . PHP_EOL;
        }

        echo '    ReadOnly:  ' . $row['readOnly'] . PHP_EOL;
        echo '    Link:      ' . $row['link'] . PHP_EOL;
        echo str_repeat('-', 100) . PHP_EOL;
    }
}

try {
    echo "Smartbox REST: $baseUrl" . PHP_EOL;
    echo 'Lade /rest/items ...' . PHP_EOL;
    $rawData = [];
    $items = safeLoadItemsRaw($baseUrl, $baseUrlExplicit, $username, $password, $cookieFile, $rawData);
    printHelp();

    while (true) {
        echo PHP_EOL . 'Filter> ';
        $line = fgets(STDIN);
        if ($line === false) {
            echo PHP_EOL;
            break;
        }

        $filter = trim($line);
        if (in_array(strtolower($filter), ['q', 'quit', 'exit'], true)) {
            break;
        }

        if (in_array(strtolower($filter), ['?', 'h', 'help', 'hilfe'], true)) {
            printHelp();
            continue;
        }

        if (in_array(strtolower($filter), ['r', 'reload'], true)) {
            $items = safeLoadItemsRaw($baseUrl, true, $username, $password, $cookieFile, $rawData);
            continue;
        }

        if (in_array(strtolower($filter), ['login', 'relogin'], true)) {
            @unlink($cookieFile);
            try {
                ampereLogin($baseUrl, $username, $password, $cookieFile);
                echo 'Login erledigt.' . PHP_EOL;
            } catch (Throwable $e) {
                echo 'WARNUNG: Login fehlgeschlagen: ' . $e->getMessage() . PHP_EOL;
            }
            continue;
        }

        if (preg_match('/^jsfind\s+(.+)$/i', $filter, $matches)) {
            executeJsFind($baseUrl, trim($matches[1]), $cookieFile);
            continue;
        }

        if (str_starts_with($filter, '/')) {
            executePathCommand($baseUrl, $filter, $username, $password, $cookieFile);
            continue;
        }

        if (in_array(strtolower($filter), ['raw', 'json'], true)) {
            $file = writeRawJsonFile($rawData);
            echo "Raw JSON gespeichert: $file" . PHP_EOL;
            continue;
        }

        printItems($items, $filter);
    }
} catch (Throwable $e) {
    fwrite(STDERR, 'WARNUNG: ' . $e->getMessage() . PHP_EOL);
}
